#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM --platform=linux/amd64 phusion/baseimage:noble-1.0.0

LABEL maintainer="Joaquín Marcher <joaquin.marcher@johnnybytes.com>"

ENV DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM=xterm

RUN set -eux \
    # Add the "PHP 8.4" ppa
    && apt-get install -y software-properties-common \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 \
    && add-apt-repository -y ppa:ondrej/php \
    #--------------------------------------------------------------------------
    # Software's Installation
    #--------------------------------------------------------------------------
    #
    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
    # Install "PHP Extentions", "libraries", "Software's"
    && apt-get update \
    && apt-get upgrade -y \
    #PHP
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        php8.4-cli \
        php8.4-common \
        php8.4-curl \
        php8.4-intl \
        php8.4-xml \
        php8.4-imagick \
        php8.4-mbstring \
        php8.4-mysql \
        php8.4-pgsql \
        php8.4-soap \
        php8.4-sqlite \
        php8.4-sqlite3 \
        php8.4-zip \
        php8.4-bcmath \
        php8.4-memcached \
        php8.4-gd \
        php8.4-dev \
        pkg-config
#libs
RUN set -eux \
    && apt-get update \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        libsqlite3-dev \
        rsync \
        sqlite3 \
        git \
        curl \
        nano \
        tree \
	    zsh \
        wget
#Servers
RUN set -eux \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        mariadb-server \
	    zip \
	    unzip \
	    redis-server \
        postgresql-client \
    && apt-get clean \
    #####################################
    # Composer:
    #####################################
    # Install composer and add its bin to the PATH.
    && curl -s http://getcomposer.org/installer | php \
    && echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc \
    && mv composer.phar /usr/local/bin/composer
RUN set -eux \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        nodejs \
    && apt-get clean
    && npm install -g newman xmysql newman-reporter-xunit

#OhMyZsh
#RUN set -eux \
#    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
#    && chsh -s $(which zsh)
