#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM --platform=linux/amd64 phusion/baseimage:noble-1.0.0

LABEL maintainer="Joaquín Marcher <joaquin.marcher@johnnybytes.com>"

ENV DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM=xterm
EXPOSE 8000
EXPOSE 8181

RUN set -eux \
    # Add the "PHP 8.5" ppa
    && apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 \
    && add-apt-repository -y ppa:ondrej/php \
    #--------------------------------------------------------------------------
    # Software's Installation
    #--------------------------------------------------------------------------
    #
    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
    # Install "PHP Extentions", "libraries", "Software's"
    && apt-get update --allow-releaseinfo-change \
    && apt-get upgrade -y \
    #PHP
    && apt-get install -y --no-install-recommends --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        php8.5-cli \
        php8.5-common \
        php8.5-curl \
        php8.5-intl \
        php8.5-xml \
        php8.5-imagick \
        php8.5-mbstring \
        php8.5-mysql \
        php8.5-pgsql \
        php8.5-soap \
        php8.5-sqlite \
        php8.5-sqlite3 \
        php8.5-zip \
        php8.5-bcmath \
        php8.5-memcached \
        php8.5-gd \
        php8.5-dev \
        pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
#libs
RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends --allow-downgrades --allow-remove-essential \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        libsqlite3-dev \
        rsync \
        sqlite3 \
        git \
        curl \
        ca-certificates \
        nano \
        tree \
        zsh \
        wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN set -eux \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y --no-install-recommends --allow-downgrades --allow-remove-essential \
        nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Playwright Browsers beforehand
RUN set -eux \
    && npx playwright install --with-deps

#Servers
RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends --allow-downgrades --allow-remove-essential \
        mariadb-server \
        zip \
        unzip \
        redis-server \
        postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    #####################################
    # Composer:
    #####################################
    # Install composer and add its bin to the PATH.
    && curl -sS https://getcomposer.org/installer | php \
    && echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc \
    && mv composer.phar /usr/local/bin/composer

#enable opcache for cli
RUN set -eux \
    && echo "opcache.enable_cli=1" >> /etc/php/8.5/cli/conf.d/10-opcache.ini
