#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM --platform=linux/amd64 phusion/baseimage:focal-1.0.0

LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"

ENV DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

RUN set -eux \
    # Add the "PHP 8" ppa
    && apt-get install -y software-properties-common \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 \
    && add-apt-repository -y ppa:ondrej/php \
    # Add mariadb repo
    && add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror.lstn.net/mariadb/repo/10.3/ubuntu bionic main' \
    #
    #--------------------------------------------------------------------------
    # Software's Installation
    #--------------------------------------------------------------------------
    #
    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
    # Install "PHP Extentions", "libraries", "Software's"
    && apt-get update \
    && apt-get upgrade -y \
    #PHP
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        php8.0-cli \
        php8.0-common \
        php8.0-curl \
        php8.0-intl \
        php8.0-xml \
        php8.0-imagick \
        php8.0-mbstring \
        php8.0-mysql \
        php8.0-pgsql \
        php8.0-soap \
        php8.0-sqlite \
        php8.0-sqlite3 \
        php8.0-zip \
        php8.0-bcmath \
        php8.0-memcached \
        php8.0-gd \
        php8.0-dev \
        pkg-config
#libs
RUN set -eux \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        libsqlite3-dev \
        rsync \
        sqlite3 \
        git \
        curl \
        vim \
        nano \
        tree \
        wget
#Servers        
RUN set -eux \
    && apt-get install -y --allow-downgrades --allow-remove-essential \        
        mariadb-server-10.3 \
	    zip \
	    unzip \
	    redis-server \
        postgresql-client \
    && apt-get clean \
    #####################################
    # Composer:
    #####################################
    # Install composer and add its bin to the PATH.
    && curl -s http://getcomposer.org/installer | php \
    && echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc \
    && mv composer.phar /usr/local/bin/composer
RUN set -eux \
    && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        nodejs \
    && apt-get clean \    
    && npm install -g newman xmysql newman-reporter-xunit        
