#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM --platform=linux/amd64 phusion/baseimage:focal-1.0.0

LABEL maintainer="Joaquín Marcher <joaquin.marcher@johnnybytes.com>"

ENV DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

RUN set -eux \
    # Add the "PHP 8.2" ppa
    && apt-get install -y software-properties-common \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 \
    && add-apt-repository -y ppa:ondrej/php \
    # Add mariadb repo
    #
    #--------------------------------------------------------------------------
    # Software's Installation
    #--------------------------------------------------------------------------
    #
    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
    # Install "PHP Extentions", "libraries", "Software's"
    && apt-get update \
    && apt-get upgrade -y \
    #PHP
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        php8.2-cli \
        php8.2-common \
        php8.2-curl \
        php8.2-intl \
        php8.2-xml \
        php8.2-imagick \
        php8.2-mbstring \
        php8.2-mysql \
        php8.2-pgsql \
        php8.2-soap \
        php8.2-sqlite \
        php8.2-sqlite3 \
        php8.2-zip \
        php8.2-bcmath \
        php8.2-memcached \
        php8.2-gd \
        php8.2-dev \
        pkg-config
#libs
RUN set -eux \
    && apt-get update \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        libsqlite3-dev \
        rsync \
        sqlite3 \
        git \
        curl \
        nano \
        tree \
	zsh \
        wget
#Servers
RUN set -eux \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        mariadb-server \
	    zip \
	    unzip \
	    redis-server \
        postgresql-client \
    && apt-get clean \
    #####################################
    # Composer:
    #####################################
    # Install composer and add its bin to the PATH.
    && curl -s http://getcomposer.org/installer | php \
    && echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc \
    && mv composer.phar /usr/local/bin/composer
RUN set -eux \
    && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        nodejs \
    && apt-get clean \
    && npm install -g newman xmysql newman-reporter-xunit
#OhMyZsh
RUN set -eux \
    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    && chsh -s $(which zsh)

#Golang & Stripe-mock
RUN set -eux \
    && apt-get update --fix-missing && apt-get install -y --allow-downgrades \
        golang \
    && go install github.com/stripe/stripe-mock@latest

RUN set -eux \
    && curl -fsSL https://jb.gg/qodana-cli/install | bash
RUN set -eux \
    && apt-get update --fix-missing && apt-get install -y --allow-downgrades \
     --allow-remove-essential libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 \
     libnss3 libxss1 libasound2 libxtst6 xauth xvfb
