#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM --platform=linux/amd64 phusion/baseimage:noble-1.0.0

LABEL maintainer="Joaquín Marcher <joaquin.marcher@johnnybytes.com>"

ENV DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm
EXPOSE 8000
EXPOSE 8181

RUN set -eux \
    # Add the "PHP 8.3" ppa
    && apt-get install -y software-properties-common \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 \
    && add-apt-repository -y ppa:ondrej/php \
    #--------------------------------------------------------------------------
    # Software's Installation
    #--------------------------------------------------------------------------
    #
    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
    # Install "PHP Extentions", "libraries", "Software's"
    && apt-get update --allow-releaseinfo-change \
    && apt-get upgrade -y \
    #PHP
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        php8.3-cli \
        php8.3-common \
        php8.3-curl \
        php8.3-intl \
        php8.3-xml \
        php8.3-imagick \
        php8.3-mbstring \
        php8.3-mysql \
        php8.3-pgsql \
        php8.3-soap \
        php8.3-sqlite \
        php8.3-sqlite3 \
        php8.3-zip \
        php8.3-bcmath \
        php8.3-memcached \
        php8.3-gd \
        php8.3-dev \
        pkg-config
#libs
RUN set -eux \
    && apt-get update \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        libsqlite3-dev \
        rsync \
        sqlite3 \
        git \
        curl \
        nano \
        tree \
	    zsh \
        wget

RUN set -eux \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
          nodejs

# Download Playwright Browsers beforehand
RUN set -eux \
    && npx playwright install \
    && npx playwright install-deps

#Servers
RUN set -eux \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        mariadb-server \
	    zip \
	    unzip \
	    redis-server \
        postgresql-client \
    && apt-get clean \
    #####################################
    # Composer:
    #####################################
    # Install composer and add its bin to the PATH.
    && curl -s http://getcomposer.org/installer | php \
    && echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc \
    && mv composer.phar /usr/local/bin/composer



#enable opcache for cli
RUN set -eux \
    && echo "opcache.enable_cli=1" >> /etc/php/8.3/cli/conf.d/10-opcache.ini
